# Generated by Django 5.0.1 on 2024-05-26 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_panchayath'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='panchayath',
            old_name='panchayath_password',
            new_name='password',
        ),
        migrations.AddField(
            model_name='panchayath',
            name='district',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panchayath_district', to='master.district'),
        ),
        migrations.AddField(
            model_name='panchayath',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='panchayath',
            name='user',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panchayath_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
