# Generated by Django 5.0.1 on 2024-05-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_rename_panchayath_password_panchayath_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayath',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50, null=True),
        ),
    ]
