# Generated by Django 5.0.1 on 2024-05-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_corporation_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panchayath',
            name='password',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
