# Generated by Django 4.0 on 2024-05-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_alter_panchayath_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muncipality',
            name='password',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
